version: '2'

networks:
  microservices-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper-container
    ports:
     - "2181:2181"
    networks:
     - microservices-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-container:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test-topic:1:1,clicks_topic:1:1,favorites_topic:1:1,impressions_topic:1:1,leads_topic:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
    networks:
     - microservices-network
